"""name=init

Revision ID: 373a8d262e57
Revises: 
Create Date: 2025-06-09 11:54:58.391210

"""
from typing import Tuple, Optional

from alembic import op
import sqlalchemy as sa


# 修订版本标识符，由Alembic使用
revision = '373a8d262e57'
down_revision = None
branch_labels = None
depends_on = None

# 迁移描述信息
description = "name=init"


def upgrade() -> None:
    """升级数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('memory', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_user_id'), 'agent_memory', ['user_id'], unique=False)
    op.create_table('agent_storage',
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('team_session_id', sa.String(length=255), nullable=True),
    sa.Column('agent_data', sa.JSON(), nullable=False, comment='Agent data'),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('memory', sa.JSON(), nullable=False, comment='Session memory'),
    sa.Column('session_data', sa.JSON(), nullable=False, comment='Session data'),
    sa.Column('extra_data', sa.JSON(), nullable=False, comment='Extra data'),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_agent_storage_agent_id'), 'agent_storage', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_storage_team_session_id'), 'agent_storage', ['team_session_id'], unique=False)
    op.create_index(op.f('ix_agent_storage_user_id'), 'agent_storage', ['user_id'], unique=False)
    op.create_table('team_memory',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('memory', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_memory_user_id'), 'team_memory', ['user_id'], unique=False)
    op.create_table('team_storage',
    sa.Column('team_id', sa.String(length=255), nullable=True),
    sa.Column('team_session_id', sa.String(length=255), nullable=True),
    sa.Column('team_data', sa.JSON(), nullable=False, comment='Team data'),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('memory', sa.JSON(), nullable=False, comment='Session memory'),
    sa.Column('session_data', sa.JSON(), nullable=False, comment='Session data'),
    sa.Column('extra_data', sa.JSON(), nullable=False, comment='Extra data'),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_team_storage_team_id'), 'team_storage', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_storage_team_session_id'), 'team_storage', ['team_session_id'], unique=False)
    op.create_index(op.f('ix_team_storage_user_id'), 'team_storage', ['user_id'], unique=False)
    op.create_table('user_memory',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=False),
    sa.Column('memory_value', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'memory_key', name='uq_user_memory_user_key')
    )
    op.create_index('idx_user_memory_user_id_key', 'user_memory', ['user_id', 'memory_key'], unique=False)
    op.create_index(op.f('ix_user_memory_user_id'), 'user_memory', ['user_id'], unique=False)
    op.create_table('workflow_storage',
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_data', sa.JSON(), nullable=False, comment='Team data'),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('memory', sa.JSON(), nullable=False, comment='Session memory'),
    sa.Column('session_data', sa.JSON(), nullable=False, comment='Session data'),
    sa.Column('extra_data', sa.JSON(), nullable=False, comment='Extra data'),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_workflow_storage_user_id'), 'workflow_storage', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_storage_workflow_id'), 'workflow_storage', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_storage_workflow_id'), table_name='workflow_storage')
    op.drop_index(op.f('ix_workflow_storage_user_id'), table_name='workflow_storage')
    op.drop_table('workflow_storage')
    op.drop_index(op.f('ix_user_memory_user_id'), table_name='user_memory')
    op.drop_index('idx_user_memory_user_id_key', table_name='user_memory')
    op.drop_table('user_memory')
    op.drop_index(op.f('ix_team_storage_user_id'), table_name='team_storage')
    op.drop_index(op.f('ix_team_storage_team_session_id'), table_name='team_storage')
    op.drop_index(op.f('ix_team_storage_team_id'), table_name='team_storage')
    op.drop_table('team_storage')
    op.drop_index(op.f('ix_team_memory_user_id'), table_name='team_memory')
    op.drop_table('team_memory')
    op.drop_index(op.f('ix_agent_storage_user_id'), table_name='agent_storage')
    op.drop_index(op.f('ix_agent_storage_team_session_id'), table_name='agent_storage')
    op.drop_index(op.f('ix_agent_storage_agent_id'), table_name='agent_storage')
    op.drop_table('agent_storage')
    op.drop_index(op.f('ix_agent_memory_user_id'), table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ### 